spring:
  datasource:
    url: jdbc:mysql://localhost:3306/complaintmechanismsystem
    username: root
    password: 629541
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  error:
    include-exception: true
    include-stacktrace: always
  session:
    cookie:
      name: MYSESSIONID