spring:
  datasource:
    url: jdbc:mysql://localhost:3306/complaintmechanismsystem
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  servlet:
    multipart:
      max-request-size: 40GB
      max-file-size: 10GB

server:
  error:
    include-exception: true
    include-stacktrace: always


